version: "3.9"

services:
  backend-ml:
    build: ./backend
    container_name: backend-ml
    ports:
      - "8000:8000"

  frontend-ml:
    build: ./frontend
    container_name: frontend-ml
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend-ml:8000